package AIINterview.CareerVerse.AI.dto;

import java.util.List;

public record SessionResponse(
        Long sessionId,
        String role,
        String difficulty,
        String status,
        int currentQuestionIndex,
        int totalQuestions,
        int completed,
        int remaining,
        /** Personalized AI interviewer greeting generated by Gemini */
        String interviewerIntro,
        List<QuestionDto> questions
) {}
